//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIStudyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalText
    {
        public int AnimalId { get; set; }
        public string AnimalName { get; set; }
        public string AnimalDetails { get; set; }
        public string Url { get; set; }
        public string LoremText { get; set; }
    }
}
