//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIStudyApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APIStudyAppDatabaseEntities : DbContext
    {
        public APIStudyAppDatabaseEntities()
            : base("name=APIStudyAppDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<AnimalDetail> AnimalDetail { get; set; }
        public virtual DbSet<AnimalText> AnimalText { get; set; }
        public virtual DbSet<blog_posts> blog_posts { get; set; }
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<LoremText> LoremText { get; set; }
        public virtual DbSet<LoremTextComma> LoremTextComma { get; set; }
        public virtual DbSet<Keys> Keys { get; set; }
    }
}
