//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIStudyApp.Models
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Represents a Lorem text and specific lorem words.
    /// </summary>
    public partial class LoremText
    {
        /// <summary>
        /// Specific number of lorem words
        /// </summary>
        public int numberOfWords { get; set; }
        /// <summary>
        /// Full Lorem text
        /// </summary>
        public string Lorem { get; set; }
    }
}
